"""Turn an authored lessons JSON file into SQL you can paste into Supabase.

    uv run python -m app.lessons_to_sql lessons.json > sql/seed_lessons.sql

Validates every lesson first, so a malformed file fails here rather than halfway
through a paste into the SQL editor. Slugs must be unique within the file.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

from pydantic import BaseModel, Field, ValidationError, field_validator

CATEGORIES = {"basics", "food", "insulin", "exercise", "troubleshooting", "daily-life"}


class LessonIn(BaseModel):
    model_config = {"extra": "forbid"}

    slug: str = Field(pattern=r"^[a-z0-9]+(-[a-z0-9]+)*$", max_length=80)
    title: str = Field(min_length=1, max_length=160)
    summary: str = Field(min_length=1, max_length=400)
    category: str
    difficulty: int = Field(ge=1, le=4)
    estimated_minutes: int = Field(ge=1, le=60)
    key_takeaways: list[str] = Field(min_length=1, max_length=6)
    body: str = Field(min_length=1)

    @field_validator("category")
    @classmethod
    def known_category(cls, v: str) -> str:
        if v not in CATEGORIES:
            raise ValueError(f"category must be one of {sorted(CATEGORIES)}")
        return v


class LessonFile(BaseModel):
    lessons: list[LessonIn] = Field(min_length=1)

    @field_validator("lessons")
    @classmethod
    def unique_slugs(cls, v: list[LessonIn]) -> list[LessonIn]:
        seen = set()
        for lesson in v:
            if lesson.slug in seen:
                raise ValueError(f"duplicate slug: {lesson.slug}")
            seen.add(lesson.slug)
        return v


def q(value: str) -> str:
    """Single-quote a string for SQL, doubling any embedded quotes."""
    return "'" + value.replace("'", "''") + "'"


def to_sql(parsed: LessonFile) -> str:
    rows = []
    for index, lesson in enumerate(parsed.lessons):
        rows.append(
            "  (gen_random_uuid(), {slug}, {title}, {summary}, {category}, "
            "{difficulty}, {minutes}, {body}, {takeaways}::json, {order}, TRUE)".format(
                slug=q(lesson.slug),
                title=q(lesson.title),
                summary=q(lesson.summary),
                category=q(lesson.category),
                difficulty=lesson.difficulty,
                minutes=lesson.estimated_minutes,
                body=q(lesson.body),
                takeaways=q(json.dumps(lesson.key_takeaways)),
                order=index,
            )
        )

    return "\n".join(
        [
            "-- Generated by app/lessons_to_sql.py — do not edit by hand.",
            f"-- {len(parsed.lessons)} lesson(s). Re-running updates existing rows by slug.",
            "",
            "INSERT INTO lessons (id, slug, title, summary, category, difficulty,",
            "                     estimated_minutes, body, key_takeaways, order_index, published)",
            "VALUES",
            ",\n".join(rows),
            "ON CONFLICT (slug) DO UPDATE SET",
            "  title             = EXCLUDED.title,",
            "  summary           = EXCLUDED.summary,",
            "  category          = EXCLUDED.category,",
            "  difficulty        = EXCLUDED.difficulty,",
            "  estimated_minutes = EXCLUDED.estimated_minutes,",
            "  body              = EXCLUDED.body,",
            "  key_takeaways     = EXCLUDED.key_takeaways,",
            "  order_index       = EXCLUDED.order_index,",
            "  published         = EXCLUDED.published;",
            "",
        ]
    )


def main() -> int:
    if len(sys.argv) != 2:
        print(__doc__, file=sys.stderr)
        return 2

    path = Path(sys.argv[1])
    try:
        raw = json.loads(path.read_text())
    except FileNotFoundError:
        print(f"No such file: {path}", file=sys.stderr)
        return 1
    except json.JSONDecodeError as exc:
        print(f"{path} is not valid JSON: {exc}", file=sys.stderr)
        return 1

    try:
        parsed = LessonFile.model_validate(raw)
    except ValidationError as exc:
        print(f"{path} does not match the lesson schema:\n{exc}", file=sys.stderr)
        return 1

    print(to_sql(parsed))
    print(f"Validated {len(parsed.lessons)} lesson(s).", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
