-- Generated by app/lessons_to_sql.py — do not edit by hand.
-- 12 lesson(s). Re-running updates existing rows by slug.

INSERT INTO lessons (id, slug, title, summary, category, difficulty,
                     estimated_minutes, body, key_takeaways, order_index, published)
VALUES
  (gen_random_uuid(), 'what-blood-glucose-is', 'What blood glucose is and what moves it', 'Where glucose comes from, what takes it out of the blood, and why type 1 changes the balance.', 'basics', 1, 4, '## Glucose is a fuel in transit

Glucose is a simple sugar that your body runs on. Your brain in particular has almost no ability to store fuel, so it needs a steady supply arriving through the bloodstream at all times.

The blood is not where glucose is stored. It is the delivery route. At any moment an adult has only about four grams of glucose dissolved in their entire bloodstream, roughly a teaspoon. That small pool is constantly being topped up and constantly being drained, and what you see on a meter or a continuous glucose monitor is the level in that pool right now.

This is the single most useful idea in diabetes: your glucose level is not a thing in itself. It is the running balance between glucose coming in and glucose going out.

## What puts glucose in

Two sources.

**Food.** Carbohydrate in what you eat is broken down into glucose and absorbed from the gut. This is the obvious one, and the one you have most direct awareness of.

**Your liver.** This one surprises people. Your liver holds a store of glucose and releases it steadily, all day and all night, to keep the brain supplied between meals. It releases more when you are stressed, when you are ill, and in the early hours of the morning. Overnight, when you have eaten nothing for eight hours, essentially all the glucose arriving in your blood came from your liver.

## What takes glucose out

Cells across your body absorb glucose and burn it. Muscle is the biggest consumer, and muscle that is working takes up far more than muscle at rest.

Most cells cannot pull glucose in on their own. They need a signal, and that signal is insulin. Insulin is a hormone made by beta cells in the pancreas, and its job is to tell cells that glucose is available and they should take it in. Without insulin, glucose stays in the blood no matter how much of it is there and no matter how much the cells need it.

Insulin also tells the liver to stop releasing its stored glucose. So it works on both sides of the balance at once: more out, less in.

## What type 1 changes

In type 1 diabetes the immune system destroys the beta cells, so the pancreas makes little or no insulin. Nothing else about the system is broken. Food still turns into glucose. The liver still does its job. Cells still want fuel and can still use it.

What is missing is the signal. That is why glucose rises after eating with no insulin present, and why it keeps rising even overnight when you have not eaten. The liver keeps supplying, and without insulin nothing tells it to stop or tells the cells to take the glucose up.

So the balance still has to be struck, but the insulin side of it now arrives from outside the body, by injection or pump. That is a genuinely harder problem than the one a working pancreas solves, because a pancreas adjusts second by second based on what it senses, and injected insulin cannot be taken back once it is in.

## A worked example

Hypothetical: Sam has type 1 and eats a bowl of porridge at 8am with no insulin on board.

Carbohydrate from the porridge starts being absorbed within about fifteen minutes. Glucose flows into the blood. Sam''s cells cannot take it up, because there is no insulin to tell them to. His liver, also not hearing any insulin signal, carries on releasing its own glucose on top.

Inflow is high, outflow is near zero, and the level climbs, perhaps from 6 mmol/L (108 mg/dL) to well above 15 mmol/L (270 mg/dL) over the next couple of hours. The glucose is not being used. It is stuck in transit.

This is illustrating the mechanism, not describing what anyone should do. How much insulin any individual takes for a meal is worked out with their diabetes team.

## In practice

When your glucose does something you did not expect, the question to ask is not what is my number. It is which side of the balance changed.

Did more come in than you accounted for, from food or from a liver responding to stress or illness? Did less go out than usual, because you moved less or because insulin was absorbing poorly? Almost every pattern you will meet in the rest of these lessons is a variation on that one question, and having the frame makes the answers much easier to see.', '["Glucose enters the blood from food and from the liver.", "Insulin is the signal that lets cells take glucose out of the blood.", "In type 1 the pancreas makes little or no insulin, so the balance is managed from outside.", "Almost everything that affects glucose does so by changing either the inflow or the outflow."]'::json, 0, TRUE),
  (gen_random_uuid(), 'target-ranges-and-time-in-range', 'Target ranges and time in range', 'What the usual glucose targets are, where they come from, and why time in range tells you more than an average does.', 'basics', 1, 4, '## The band most people use

International consensus guidance defines a standard target range of 3.9 to 10.0 mmol/L, which is 70 to 180 mg/dL. Continuous glucose monitors and their apps report against this band by default, which is why you see those numbers everywhere.

The edges are not arbitrary. The lower one sits a little above the point where most people start to notice symptoms of a low, giving some margin. The upper one is roughly where glucose starts to spill into the urine and where the long-term effects of high glucose begin to accumulate meaningfully.

During pregnancy the range is tighter, and for some people, such as those who are older or who have lost their ability to sense lows, a slightly higher and safer band is deliberately used. Your own targets are a clinical decision made with your team, not something to infer from an app default.

## Why the average is not enough

Before CGMs, the standard measure was HbA1c, which reflects roughly the average glucose over the previous two to three months. It is still useful and still used, but it has a blind spot that matters a lot day to day.

An average tells you nothing about spread. Consider two hypothetical people who both average 8.5 mmol/L (153 mg/dL) over a week.

The first sits between 6 and 11 mmol/L (108 to 198 mg/dL) almost all the time. Steady, unremarkable days.

The second spends mornings at 3.2 mmol/L (58 mg/dL), treats the low, rebounds to 16 mmol/L (288 mg/dL) by lunch, comes back down by evening, and repeats. Same average. A completely different experience, and one with real risk in it.

An average cannot tell those two weeks apart. Time in range can.

## Reading the four numbers

Most CGM reports break the day into bands. The commonly cited targets for a non-pregnant adult with type 1 are:

| Band | Common target |
| --- | --- |
| Time in range, 3.9 to 10.0 mmol/L (70 to 180 mg/dL) | more than 70% of the day |
| Time above 10.0 mmol/L (180 mg/dL) | less than 25% |
| Time below 3.9 mmol/L (70 mg/dL) | less than 4% |
| Time below 3.0 mmol/L (54 mg/dL) | less than 1% |

Seventy percent of a day is about seventeen hours. That is a deliberate choice by the people who wrote the guidance. It is meant to be achievable rather than perfect, because a target nobody can hit is not a useful target.

## The bottom bands carry more weight

The percentages get smaller as you go down the table, and that is the point. High glucose does its damage slowly, over years. Low glucose does its damage in minutes, and severe lows are immediately dangerous.

So the two bottom rows are not just extra detail. Reducing time below range is generally the first thing to look at, and an improvement in time in range that comes from spending more time low is not an improvement at all.

This is also why chasing a very high time in range can backfire. Pushing the average down by running close to the lower edge buys you a better-looking headline number and more lows. The shape of the day matters more than the score.

## In practice

When you look at a week of data, read it in this order.

First, time below range. If there are lows, that is where the attention goes, regardless of what the rest of the report says.

Second, when the highs happen rather than how many there are. Highs clustered after breakfast are a different problem from highs that build overnight, and the pattern points at the cause.

Third, the headline percentage, which is really just a summary of the first two.

One more thing worth holding onto: these numbers describe a population, not you on a Tuesday. A single day outside the band is weather. A pattern repeating across a fortnight is climate, and that is what is worth taking to your team.', '["The commonly used range is 3.9 to 10.0 mmol/L, or 70 to 180 mg/dL.", "Time in range is the share of the day spent inside that band.", "An average can look fine while hiding large swings in both directions.", "Time below range matters more than time above, hour for hour.", "Your own targets are set with your diabetes team and may differ."]'::json, 1, TRUE),
  (gen_random_uuid(), 'reading-cgm-trend-arrows', 'Reading CGM trend arrows', 'Why the arrow on a CGM often matters more than the number, and why the reading is always a little behind the truth.', 'basics', 2, 5, '## Two pieces of information, not one

A continuous glucose monitor gives you a number and an arrow. People new to CGM tend to read the number and skim the arrow, which is the wrong way round more often than not.

Consider 5.5 mmol/L (99 mg/dL). On its own that looks ideal, comfortably mid-range.

Now add an arrow. With a flat arrow, it is exactly what it looks like. With a steeply falling arrow, it is a low that has not happened yet: at that rate of fall the same reading is heading below range within about fifteen minutes. Same number, entirely different situation.

The arrow is a rate of change, and rate of change is what lets you see slightly into the future. That is the real advantage a CGM has over fingersticks, which give you a series of disconnected snapshots with no direction attached.

## What the arrows mean

The exact icons vary by manufacturer, but the underlying scale is broadly consistent.

| Arrow | Rate of change | Over 30 minutes |
| --- | --- | --- |
| Steady | under 0.06 mmol/L per min (1 mg/dL) | little movement |
| Slowly rising or falling | 0.06 to 0.11 mmol/L per min (1 to 2 mg/dL) | around 2 to 3 mmol/L (35 to 60 mg/dL) |
| Rising or falling | 0.11 to 0.17 mmol/L per min (2 to 3 mg/dL) | around 3 to 5 mmol/L (60 to 90 mg/dL) |
| Rapidly rising or falling | over 0.17 mmol/L per min (3 mg/dL) | 5 mmol/L (90 mg/dL) or more |

The useful habit is to read the pair together as a short sentence. Not 5.5, but 5.5 and falling steadily, so somewhere near 3.5 mmol/L (63 mg/dL) in half an hour if nothing changes.

That if nothing changes is doing a lot of work, and it is worth being honest about. The arrow is an extrapolation of the last several minutes. It is not a forecast, and glucose curves bend.

## Why the reading lags

A CGM does not measure blood. The sensor filament sits in the interstitial fluid, the fluid in the spaces between cells just under the skin, and measures glucose there.

Glucose reaches that fluid by diffusing out of nearby capillaries, which takes time. So interstitial glucose follows blood glucose with a delay of roughly five to fifteen minutes, depending on the person, the sensor and how well that patch of skin is perfused.

The consequence is not intuitive but it matters: **the lag is worst exactly when things are moving fastest.** When you are flat, blood and interstitial glucose have had time to equalise and the reading is close to true. When you are dropping quickly, the sensor is reporting where your blood was ten minutes ago, and your blood is now lower than the screen says.

So a rapidly falling arrow understates how low you already are, and a rapidly rising arrow understates how high. The arrow is not just extra context in those moments. It is a correction to the number.

## A worked example

Hypothetical: Priya glances at her phone and sees 4.8 mmol/L (86 mg/dL) with a rapidly falling arrow.

Reading the number alone, she is in range. Reading the pair, two separate things are true. Her actual blood glucose right now is probably already below what the screen shows, because of the lag. And it is falling at more than 0.17 mmol/L per minute, so it will be lower again shortly.

The number said in range. The full reading said heading out of range and already further along than displayed.

What she does about it is a matter for her own hypo plan, agreed with her diabetes team. The lesson here is only about what the display is telling her.

## When to check with a fingerstick

CGMs are good, and modern ones are good enough that most people rarely need fingersticks. There are still moments where a blood test is the more reliable source.

When the reading contradicts how you feel, trust the symptoms and check. When you are low and want to confirm recovery, the lag means the sensor will be the last to show it. And in the first hours after a new sensor, readings tend to be less settled while the tissue around the filament recovers from insertion.

## In practice

Train yourself to say the arrow out loud with the number. It takes a week to become automatic and it changes what you notice.

Give extra weight to arrows overnight, when there is nobody watching the screen for hours at a time. And remember that a flat arrow after a meal is not the same as a flat arrow at 3am, because one means the rise has finished and the other means nothing is happening at all.', '["The number tells you where you are; the arrow tells you where you are heading.", "A CGM measures fluid between cells, not blood, so it lags by roughly 5 to 15 minutes.", "The lag is largest exactly when glucose is changing fastest.", "The same number with different arrows describes two completely different situations."]'::json, 2, TRUE),
  (gen_random_uuid(), 'counting-carbohydrate', 'Counting carbohydrate', 'What actually counts as carbohydrate, how people estimate it in real meals, and why the estimate is always approximate.', 'food', 2, 5, '## Why carbohydrate specifically

Food contains carbohydrate, protein and fat. All three carry energy, but they do not affect blood glucose in the same way or on the same timescale.

Carbohydrate is broken down into glucose and absorbed into the blood, most of it within two hours. That is a direct route and a fairly predictable one.

Protein and fat can influence glucose too, but indirectly, more slowly, and much less consistently. That is a lesson of its own.

So carbohydrate counting is not a claim that carbohydrate is the only thing that matters. It is a claim that it is the part that matters most and the part you can most reliably predict, which makes it the sensible thing to count.

## What to count

On a packaged food label in the UK and Europe, the line marked carbohydrate is the number you want. Of which sugars, sitting underneath it, is a subset already included in the total, not something to add on.

In the United States, labels list total carbohydrate with fibre listed separately underneath but still included in the total.

### Fibre

Fibre is a carbohydrate your body cannot break down into glucose. It passes through largely intact.

So a food with 30g carbohydrate of which 8g is fibre delivers closer to 22g of glucose-raising carbohydrate. For most meals the difference is small enough to ignore, but for genuinely high-fibre foods such as pulses, some breads and many high-fibre cereals it becomes worth accounting for. Whether and how you adjust for it is something to work out with your diabetes team, since practice varies.

### Sugar alcohols

Sweeteners ending in -ol, such as maltitol, sorbitol and xylitol, appear in sugar-free products. They are partially absorbed and raise glucose less than sugar does, but not by zero, and they vary a lot between types. Sugar-free does not mean carbohydrate-free.

## Estimating without a label

Most meals do not come with a label. Three approaches, usually mixed.

**Weighing.** Most accurate, most tedious, and worth doing for a while even if you do not intend to keep it up. Weighing your usual portions for a fortnight calibrates your eye far better than reading tables does.

**Reference portions.** Learning a handful of common items and scaling from them. A medium slice of bread is around 15 to 20g. A medium apple around 15 to 20g. Rough anchors that you adjust by eye.

**Hand measures.** A cupped handful of cooked rice or pasta, a fist-sized potato. Least accurate, always available, and better than not counting at all.

### The cooked weight trap

Dry pasta and rice absorb a great deal of water. 100g of dry pasta is around 70g of carbohydrate; 100g of the same pasta cooked is around 25g, because most of the added weight is water.

This single confusion causes more mis-estimates than any other. If you weigh, decide whether you are weighing raw or cooked and use a value that matches.

## A worked example

Hypothetical: Marcus is eating a sandwich, an apple and a small packet of crisps.

Two slices of medium bread, around 15g each, so 30g. An apple, around 15g. A 25g bag of crisps, around 13g on the label. Total around 58g, which he would call 60.

He has not counted the cheese or butter in the sandwich, because neither contains meaningful carbohydrate. He rounded to a round number, because the underlying estimate is not precise enough for the extra digit to mean anything.

What he does with that number is between him and his diabetes team. This example is about arriving at the number.

## Consistent beats accurate

Everyone estimating carbohydrate is wrong some of the time. The useful distinction is between being wrong in a pattern and being wrong at random.

If your usual bowl of pasta always turns out to run higher than expected, that is a pattern. Patterns are visible in your data and can be corrected once you spot them.

If you count the same meal as 40g on Monday and 70g on Thursday, nothing in your data means anything, because the input changed without you knowing. So a consistent method, even a rough one, is more valuable than an accurate method you apply unevenly.

## In practice

Pick a small number of meals you eat often and get those genuinely right, by weighing them once and remembering the answer. Those few meals will cover a surprising share of your week.

Write the estimate down at the time, not from memory later. When a meal does something unexpected, the first question is whether the glucose response was odd or whether the count was, and you cannot answer that without the original number.

And keep the eye calibrated. Estimates drift over months, especially portion sizes, so it is worth going back to the scales occasionally even once you feel fluent.', '["Carbohydrate is the component of food that reliably becomes blood glucose.", "Fibre is carbohydrate on the label but is largely not absorbed as glucose.", "Cooked weight and raw weight are very different for pasta, rice and potatoes.", "Estimating is a skill that improves with feedback, and being consistently wrong is more fixable than being randomly wrong."]'::json, 3, TRUE),
  (gen_random_uuid(), 'fast-and-slow-carbohydrate', 'Fast and slow carbohydrate', 'Why the same amount of carbohydrate can arrive in twenty minutes or over three hours, and what changes the speed.', 'food', 2, 5, '## Amount and speed are separate questions

Counting carbohydrate answers how much glucose is on its way. It does not answer how fast it arrives, and those two things shape the curve differently.

Forty grams of glucose from a sugary drink and forty grams from a bowl of lentils deliver the same total. The drink delivers it over about twenty minutes, producing a sharp spike. The lentils deliver it over two to three hours, producing a slow, low hill.

Same area under the curve. Very different curves. The difference is speed, and speed is what determines whether a meal is easy or awkward to match with insulin.

## What makes carbohydrate fast

**Liquid form.** A drink empties from the stomach in minutes and needs no breaking down. Fruit juice, sugary drinks and glucose tablets dissolved in water are the fastest carbohydrate there is, which is exactly why liquids are used in hypo treatment.

**Simple structure.** Glucose and sucrose need little or no digestion. Starch needs to be broken into glucose first, which takes enzymes and time.

**Processing.** Grinding, refining and cooking all do part of the digestive work in advance. Flour is faster than the intact grain it came from. White bread is faster than a dense wholegrain loaf.

**Cooking.** Heat and water make starch granules swell and become far easier for enzymes to reach. A well-boiled potato is meaningfully faster than a firmer one, and softly cooked pasta is faster than pasta cooked al dente.

## What makes it slow

**Fibre.** It thickens the contents of the gut and physically slows the rate at which everything else is absorbed. Whole fruit is slower than the juice of the same fruit, and this is most of the reason why.

**Fat.** Fat slows the rate at which the stomach empties. A carbohydrate eaten with fat arrives later and over a longer stretch than the same carbohydrate eaten alone.

**Protein.** Also slows stomach emptying, though less dramatically than fat.

**Acidity.** Vinegar, lemon juice and the acid in sourdough all slow stomach emptying. Sourdough bread is consistently slower than the same flour in a standard loaf.

**Intact structure.** Whole grains, beans and pulses keep their cell walls, and enzymes have to get through those before reaching the starch. This is why lentils are one of the slowest common carbohydrates.

**Temperature history.** Cooked starch that has been cooled forms some resistant starch, which behaves partly like fibre. Cooked and cooled potato or rice is slower than the same food eaten hot, and reheating only partly undoes it.

## A worked example

Hypothetical: Ana eats 40g of carbohydrate on three different days.

Day one, a glass of apple juice. Absorption starts within about ten minutes and is essentially finished by forty. A steep, tall, brief peak.

Day two, two apples. The same sugars, now packaged inside fibre and cell walls, and needing to be chewed and broken down. The rise starts later, climbs less steeply and takes around two hours to complete.

Day three, a portion of lentils with olive oil. Fibre, intact cell structure and fat together. The rise is slow enough that it may look almost flat at first, and it continues for three hours or more.

Three meals, the same carbohydrate count, three shapes on the graph. How anyone matches insulin to those shapes is worked out with their diabetes team, and it is not the same answer for everyone.

## Why glycaemic index is only half useful

Glycaemic index tries to capture exactly this, ranking foods by how quickly they raise glucose relative to pure glucose. As a rough ordering it is genuinely informative.

Its weakness is that it is measured on single foods eaten alone by people without diabetes, and almost nobody eats that way. Adding butter to the bread changes it. Eating the potato cold changes it. Cooking the pasta for three minutes longer changes it.

So treat it as a starting intuition about a food in isolation, and treat your own data on your own meals as the actual answer.

## In practice

When a meal produces an unexpected shape, ask about speed before you re-examine the count. A rise that came sooner and sharper than expected is often a speed story, not a quantity one.

Notice the modifiers rather than memorising foods. The same pasta, cooked differently and eaten with different things, is a different food as far as your glucose is concerned.

And if you want to see this clearly, eat the same carbohydrate count in two different forms on two different days and look at the curves side by side. It is a more convincing demonstration than any table.', '["The amount of carbohydrate sets how far glucose rises; the speed sets how sharply.", "Liquids are faster than solids, and processed is faster than whole.", "Fibre, fat, acidity and temperature all slow absorption.", "The same food can behave differently depending on how it is cooked and what it is eaten with."]'::json, 4, TRUE),
  (gen_random_uuid(), 'why-fat-and-protein-delay-the-rise', 'Why fat and protein delay the rise', 'How a high-fat or high-protein meal can look fine for two hours and then climb, and what is happening in between.', 'food', 3, 5, '## The meal that looks fine and then is not

A familiar pattern: pizza, or a curry with cream, or a large plate of ribs. Two hours after eating, glucose looks unremarkable. Four hours after, it is climbing. Six hours after, it is still elevated, and if the meal was late it is still elevated in the morning.

Nothing has gone wrong with the carbohydrate count. This is a different mechanism, or rather three of them, and they overlap.

## Mechanism one: fat slows the stomach

The stomach releases its contents into the small intestine at a controlled rate, and fat slows that rate substantially. Fat entering the small intestine triggers hormonal signals that tell the stomach to hold back.

So carbohydrate eaten alongside a lot of fat does not stop being absorbed. It is absorbed later and spread over a longer stretch.

The practical effect is that a meal you expected to peak at ninety minutes instead trickles in over four hours or more. If insulin was timed for the expected peak, it can end up finishing its work before much of the carbohydrate has even arrived, which is why some people see a dip first and a climb afterwards.

## Mechanism two: fat reduces insulin sensitivity

This one is less intuitive. A large amount of dietary fat, particularly saturated fat, makes muscle and liver cells temporarily less responsive to insulin, over a window of roughly four to eight hours.

Less responsive means the same amount of insulin has less effect than usual. So even the carbohydrate that has arrived is cleared more slowly, and the liver is less inclined to stop its own glucose output.

This is a temporary, meal-scale version of the insulin resistance seen in type 2 diabetes. It resolves on its own, but during those hours the arithmetic of the meal is genuinely different.

## Mechanism three: protein becomes glucose

Protein is mostly used for building and repair, not fuel. But the liver can convert amino acids into glucose through a process called gluconeogenesis, and it does this more when carbohydrate is scarce.

After a very large protein meal with little carbohydrate, a modest amount of that protein can appear as glucose over the following three to five hours. It is a slow trickle rather than a rise, and for a normal-sized portion of protein alongside a normal meal it is usually not noticeable.

It becomes noticeable in two situations: very large protein portions, and low-carbohydrate eating where protein makes up a much larger share of the plate.

## A worked example

Hypothetical: Tom eats a large pizza at 7pm and counts the carbohydrate carefully.

By 9pm his glucose is close to where it started, and the meal looks handled. In fact only part of the carbohydrate has been absorbed, because the fat in the cheese and base is holding the rest in his stomach.

Between 10pm and midnight the remainder arrives. At the same time his cells are in the less-responsive window from the fat load. Inflow rises just as outflow falls, and his glucose climbs to 14 mmol/L (250 mg/dL) and stays there.

By 3am the fat effect has faded and the meal has fully absorbed, and he drifts back down.

The curve is not a mistake in the count. It is the same carbohydrate arriving on a different schedule into a body that was temporarily handling it less well. What anyone does about this pattern, including any change to how insulin is timed or delivered, is worked out with their diabetes team, because the approaches differ between injections and pumps and between individuals.

## Not all fatty meals do this

The effect scales with the amount of fat, and the thresholds are individual. A little butter on toast will not produce a five-hour tail. A meal built around cheese, cream, oil or fatty meat can.

Protein-driven rises are the same story. A normal chicken breast with rice is unlikely to be the cause of anything. A very large steak with almost no carbohydrate might be.

It is worth knowing which of your own regular meals fall into this category, because they behave as a distinct type rather than as ordinary meals with an odd result.

## In practice

When you see a delayed rise, check what the meal contained before you re-check the carbohydrate count. Late climbs from high-fat meals are common enough to be the first hypothesis rather than the last.

Watch for longer than usual after these meals. A two-hour check will genuinely tell you the meal went well, and it will be wrong.

And note the meals that do it to you specifically, by name. Pizza is the standard example, but the list is personal, and knowing your own three or four is worth more than knowing the general principle.', '["Fat slows stomach emptying, pushing the carbohydrate rise later.", "Fat also makes cells temporarily less responsive to insulin.", "Protein can be converted to glucose by the liver, slowly, when there is little carbohydrate present.", "The result is a late rise several hours after eating, often long after the meal appears to have passed."]'::json, 5, TRUE),
  (gen_random_uuid(), 'why-the-immune-system-attacks-beta-cells', 'Why the immune system attacks beta cells', 'What actually goes wrong in type 1 diabetes at the level of cells and antibodies, and why it takes years before anyone notices.', 'basics', 3, 5, '## The cells in question

Scattered through the pancreas are around a million small clusters called the islets of Langerhans. Inside each islet, beta cells make insulin and alpha cells make glucagon, a hormone that does roughly the opposite.

All of that tissue together weighs about a gram. Type 1 diabetes is, in the end, the loss of about one gram of a very specific kind of cell.

## What the immune system is supposed to do

The immune system has to distinguish between things that belong to you and things that do not. During development, immune cells that react strongly against your own tissue are supposed to be deleted or suppressed. This is called self-tolerance.

In type 1 diabetes that tolerance fails for one narrow target. T cells that recognise proteins found in beta cells escape the filter, become activated, and treat those cells as foreign. They infiltrate the islets, an event visible under a microscope as insulitis, and destroy beta cells over time.

The specificity is striking. Alpha cells sitting immediately next door, inside the same islet, are left alone. The rest of the pancreas, which produces digestive enzymes, is untouched. This is not a general immune malfunction; it is a targeted one.

## The antibodies

Alongside the T cells doing the damage, the immune system produces antibodies against beta cell proteins. The main ones are directed at GAD65, IA-2, zinc transporter 8, and insulin itself.

These antibodies are probably not the main cause of destruction. What they are is evidence. They appear in the blood long before symptoms, which is why they can be used to identify the disease in progress, and why a positive antibody test is what distinguishes type 1 from type 2 in an ambiguous case.

## Why it takes so long to notice

Researchers now describe type 1 in three stages.

**Stage 1.** Two or more autoantibodies are present. Beta cells are being lost. Glucose is entirely normal. No symptoms at all.

**Stage 2.** Enough beta cell mass has gone that glucose becomes abnormal on testing, but still not enough to cause symptoms.

**Stage 3.** Clinical diagnosis. Symptoms appear: thirst, frequent urination, weight loss, fatigue.

The reason stage 3 arrives so abruptly is that the remaining beta cells compensate. They work harder and keep glucose normal while their numbers fall. Only when roughly 80 to 90 percent of the capacity is gone does the compensation fail, and then it fails quickly.

So the experience of a sudden diagnosis over a few weeks is real, but the disease underneath it had been running for months or years. What was sudden was the point at which the reserve ran out.

## The honeymoon period

After diagnosis and the start of insulin treatment, many people find their insulin needs fall for a while, sometimes dramatically, and glucose becomes unusually easy to manage. This is the honeymoon phase.

The explanation is that the surviving beta cells had been exhausted by working under extreme demand and by the toxic effect of very high glucose. Relieving that pressure lets them recover some function temporarily. They are still being destroyed, so the phase ends, typically within months to a couple of years.

This is worth knowing because the end of the honeymoon can feel like a personal failure when it is simply the underlying disease continuing on schedule.

## Genes and triggers

Susceptibility is strongly influenced by a region of chromosome 6 called the HLA complex, which controls how the immune system presents fragments of protein for inspection. Certain HLA variants, notably DR3-DQ2 and DR4-DQ8, carry most of the risk. Around fifty other genes contribute smaller amounts.

But the genes are common and the disease is not. Most people carrying high-risk HLA types never develop type 1. Genetics loads the dice; something else appears to throw them.

What that something is remains unsettled. Enteroviral infections have the most supporting evidence, and there are hypotheses involving early diet, gut microbiome and vitamin D, none of them proven. It is also why most people with type 1 have no family history at all.

One thing is clear enough to state plainly: eating sugar does not cause type 1 diabetes, and nothing a parent did or failed to do causes it. This is a common and entirely unearned source of guilt.

## Where the research is

Because the stages are now identifiable in advance, it has become possible to intervene before stage 3. An anti-CD3 antibody, teplizumab, has been shown to delay progression from stage 2 to clinical diagnosis by a median of around two years, and is approved in the United States for that purpose.

That is a delay rather than a cure, but it is the first treatment to alter the disease itself rather than replace its missing product, which makes it a genuine change in direction.

## In practice

This lesson does not change anything you do day to day. It changes how you interpret two things.

The honeymoon, if you are in it, is temporary and its ending is not your fault. And the diagnosis, however sudden it felt, was the visible end of a long process that was already underway and was not caused by anything anyone chose.', '["Type 1 is an autoimmune disease: T cells destroy the insulin-producing beta cells.", "The process runs silently for months or years before any symptoms appear.", "Symptoms typically start once around 80 to 90 percent of beta cells are gone.", "Certain genes raise susceptibility, but most people carrying them never develop it.", "Nothing you or your family did caused it."]'::json, 6, TRUE),
  (gen_random_uuid(), 'what-insulin-does-at-the-cell', 'What insulin actually does at the cell', 'Insulin is a signal rather than a fuel. What it tells cells to do, and why it does far more than move glucose.', 'insulin', 3, 5, '## A signal, not a fuel

A common mental picture has insulin as a key that unlocks a door and lets glucose in. It is a reasonable first approximation but it hides the interesting part.

Insulin is a small protein hormone that binds to a receptor sitting on the outer surface of a cell. It does not enter the cell and it does not carry glucose anywhere. What it does is change what the cell is doing, by starting a chain of chemical signals inside it.

Think of it less as a key and more as an instruction being delivered to the cell''s control room.

## The signal inside the cell

The insulin receptor spans the cell membrane. When insulin binds to the part outside, the part inside changes shape and switches on an enzyme activity, adding phosphate groups to proteins.

That starts a cascade. Receptor substrate proteins are phosphorylated, which activates an enzyme called PI3-kinase, which activates a further enzyme called Akt. Each step amplifies the last, so a small number of insulin molecules at the surface can produce a large response inside.

You do not need the names. What matters is the shape of it: one signal at the surface, amplified into a coordinated change across the whole cell.

## Glucose transporters

Glucose is water-soluble and cannot cross a cell membrane by itself. It needs a protein channel, and the family of those channels is called GLUT.

Different tissues use different members of that family, and this is the key to a lot of otherwise puzzling behaviour.

**GLUT4, in muscle and fat cells, is the insulin-dependent one.** At rest, most GLUT4 sits inside the cell, packaged in small vesicles. When Akt is activated by insulin, those vesicles move to the surface and fuse with the membrane, inserting transporters. The cell''s capacity to take up glucose can increase perhaps tenfold within minutes. When insulin falls, the transporters are pulled back inside.

**GLUT1, GLUT2 and GLUT3 do not need insulin.** They sit permanently in the membranes of the brain, red blood cells, liver and kidney.

That second point explains something important. Your brain takes up glucose regardless of insulin. So in untreated type 1, the problem is not that the brain is starved while glucose sits in the blood. It is that muscle and fat, which are the bulk of your glucose disposal capacity, cannot take up anything, so the blood level climbs with nowhere for the glucose to go.

## The other three jobs

Glucose uptake is the job insulin is famous for. It is not the only one, and possibly not the most important.

**Insulin tells the liver to stop.** Between meals the liver releases glucose to keep the brain supplied. Insulin suppresses this. A working pancreas releases a small continuous amount of insulin partly to keep that tap turned down.

**Insulin tells fat cells to stop breaking down fat.** Fat tissue continuously releases stored fat as free fatty acids for other tissues to burn. Insulin strongly suppresses that release. This turns out to be one of insulin''s most sensitive effects: it takes very little insulin to suppress fat breakdown, much less than is needed to move glucose.

**Insulin promotes storage and building.** It pushes glucose into glycogen, encourages fat storage, and promotes protein synthesis. It is the body''s overall signal that fuel is plentiful and it is time to store rather than mobilise.

## Why the fat job matters so much

Hold the last two together and something follows.

With no insulin at all, fat cells release fatty acids without restraint. The liver receives a flood of them, burns them, and converts the excess into ketones. At the same time the liver is releasing glucose freely because nothing is telling it to stop.

So the result of no insulin is not simply high glucose. It is high glucose plus rising ketones, arriving together, which is the mechanism behind diabetic ketoacidosis. That is covered properly in its own lesson.

This is also why the small background amount of insulin matters even when you are not eating. It is not there for food. It is there to hold the liver and the fat tissue in check.

## A worked example

Hypothetical: Leah has type 1 and her pump site fails silently at 2am, delivering nothing.

Within an hour or two the small amount of insulin already in her system has been used up. Her muscle cells retract their GLUT4 transporters and stop taking up glucose. Her liver, hearing no insulin signal, begins releasing glucose freely, and her glucose climbs even though she has eaten nothing.

Meanwhile her fat tissue starts releasing fatty acids without restraint, and her liver begins producing ketones from them. By morning she is both high and generating ketones, from a fault that involved no food at all.

What she should do about a suspected site failure is part of her own plan, agreed with her diabetes team. The point here is only that both problems come from the same missing signal.

## In practice

Two things are worth carrying away.

Insulin is doing several jobs at once, and the one that keeps you safe overnight is the suppression of the liver and of fat breakdown, not the movement of glucose from a meal.

And a gap in insulin supply is a different kind of event from a high reading after a meal, even when the number on the screen looks similar, because only one of them is producing ketones.', '["Insulin binds a receptor on the cell surface; it never enters the cell.", "In muscle and fat it triggers glucose transporters to move to the surface.", "Brain, liver and red blood cells take up glucose without needing insulin.", "Insulin also tells the liver to stop releasing glucose and tells fat cells to stop breaking down fat.", "That last job is why a lack of insulin causes ketones, not just high glucose."]'::json, 7, TRUE),
  (gen_random_uuid(), 'the-counter-regulatory-system', 'The hormones that push glucose up', 'Insulin has four opponents. Knowing what they are explains dawn rises, stress highs, and why lows can be followed by stubborn highs.', 'basics', 3, 5, '## Falling is more dangerous than rising

Your brain uses around 120 grams of glucose a day and stores almost none. A few minutes without supply causes confusion; longer causes unconsciousness.

High glucose, by contrast, does its damage over years.

Evolution weighted these accordingly. There is one hormone that lowers blood glucose, insulin, and at least four that raise it. The system is deliberately lopsided, because the consequences of the two failures are not remotely symmetrical.

Those four are the counter-regulatory hormones, and most unexplained glucose behaviour is one of them.

## Glucagon

Made by the alpha cells sitting alongside beta cells in the same islets. Its main target is the liver, which it tells to break down stored glycogen and release glucose, and to manufacture new glucose from other materials.

In someone without diabetes, a falling glucose level suppresses insulin and triggers glucagon within minutes, and the level recovers before anything is noticed. This happens dozens of times a day, invisibly.

In type 1 something specific goes wrong here. Within a few years of diagnosis, most people lose the glucagon response to hypoglycaemia. The alpha cells still work and still respond to other stimuli, but the local signalling from neighbouring beta cells that normally coordinates the response is gone with those cells.

So the fastest and most important defence against a low is missing, which is a large part of why lows in type 1 do not simply correct themselves.

## Adrenaline

The second line of defence, and in type 1 it becomes the first.

Adrenaline raises glucose by prompting the liver to release it and by reducing uptake into muscle. It also produces the recognisable symptoms of a low: shaking, sweating, a racing heart, anxiety.

Those symptoms are not the low itself. They are the alarm attached to the response. This distinction matters, because the alarm can be lost independently of the low, which is what hypoglycaemia unawareness is.

Adrenaline also rises for reasons unconnected with glucose. Acute stress, fear, competition, an argument, a job interview. The glucose rise that comes with it is real and has nothing to do with food.

## Cortisol and growth hormone

These two work slowly, over hours rather than minutes, and they are why some patterns are so persistent.

Cortisol raises glucose by prompting the liver to make more and by making tissues somewhat less responsive to insulin. It follows a strong daily rhythm, at its lowest around midnight and climbing steeply from roughly 3am to peak shortly after waking.

Growth hormone is released in pulses during deep sleep in the first half of the night, and it too reduces insulin sensitivity, with an effect that appears several hours later.

Together they produce the dawn phenomenon: a rise in glucose in the early hours, before eating anything, driven by hormones preparing the body to wake up. It is a normal physiological event that everyone has. In type 1 it becomes visible, because there is no pancreas quietly increasing insulin output to match.

Cortisol is also the hormone of sustained stress and of illness, which is why a bad week at work or a chest infection can raise glucose for days.

## A worked example

Hypothetical: Daniel goes low at 3am, wakes, treats it, and goes back to sleep. By 8am he is at 15 mmol/L (270 mg/dL) and cannot see why.

Three things happened at once. His adrenaline response to the low released glucose from his liver and reduced his muscle uptake, an effect that persists for hours after the low itself has passed. His cortisol and growth hormone were already climbing on their normal overnight schedule. And the carbohydrate he took to treat the low was absorbed into a body that was, for those hours, less responsive to insulin than usual.

The high is not evidence that he over-treated. It is the counter-regulatory response doing precisely what it evolved to do, which is to make sure a low does not happen again soon.

What to change, if anything, is a conversation with his diabetes team. Recognising the pattern is what stops the wrong conclusion being drawn from it.

## In practice

When glucose rises with no food involved, run through the four. Was there a low in the preceding hours? Is it the early morning? Is there stress or illness? Was there hard exercise, which raises adrenaline too?

And treat a high following a low as expected physiology rather than as a mistake. Reacting to it as though it were an error tends to produce the opposite error a few hours later.', '["Glucagon, adrenaline, cortisol and growth hormone all raise glucose.", "They exist to protect the brain from running out of fuel.", "Cortisol and growth hormone rise before waking, which is what causes the dawn rise.", "In long-standing type 1 the glucagon response to a low is often lost.", "A high after a low is usually these hormones, not something you did wrong."]'::json, 8, TRUE),
  (gen_random_uuid(), 'where-ketones-come-from', 'Where ketones come from', 'Ketones are a normal backup fuel. What turns a normal process into diabetic ketoacidosis is the absence of insulin, not the presence of ketones.', 'troubleshooting', 3, 5, '## Ketones are not a malfunction

Your brain cannot burn fatty acids. They do not cross into the brain in useful quantities. So if glucose ever ran short, the brain would be in immediate trouble.

Evolution solved this with a workaround. The liver can convert fatty acids into small molecules that do cross into the brain and can be burned there. Those are ketones.

This is a normal system that runs in everyone. It rises during fasting, during prolonged exercise, overnight, and on a very low carbohydrate diet. Someone without diabetes fasting for a day will produce ketones and be entirely fine.

So ketones are not the problem in themselves. What matters is what limits them.

## How they are made

The chain has three steps.

**Fat is released.** Fat tissue breaks down stored triglyceride and releases free fatty acids into the blood. Insulin strongly suppresses this step, and it does so at very low concentrations. Even a small amount of insulin keeps fat release largely in check.

**The liver burns them.** Fatty acids arriving at the liver are broken down into a two-carbon molecule called acetyl-CoA. Normally acetyl-CoA feeds into the citric acid cycle and is burned for energy.

**The overflow becomes ketones.** The citric acid cycle has a limited throughput, and it also needs an input derived from carbohydrate metabolism. When fatty acids arrive faster than the cycle can process them, the excess acetyl-CoA is diverted into making ketones: acetoacetate, beta-hydroxybutyrate, and acetone.

Acetone is volatile and is breathed out, which is the fruity or pear-drop smell associated with high ketones.

## Why insulin is the control valve

Notice that insulin governs the first step, the release of fat. That is the tap.

With a normal background level of insulin, fat release is restrained, the liver receives a manageable supply, and ketone production stays modest even during a fast. The system self-limits.

With no insulin, nothing restrains the tap. Fat pours out, the liver is overwhelmed, and ketone production runs at a rate it would never normally reach. At the same time the liver, also hearing no insulin, is releasing glucose freely. Both problems come from one missing signal.

This is the key asymmetry: **the amount of insulin needed to suppress ketone production is small, but it is not zero.** A gap in supply, from a failed pump site, a missed long-acting dose or an illness that raises requirements, removes it.

## What makes it acidosis

Two of the three ketones are acids. In small quantities your blood buffers them without difficulty.

At the rates reached in uncontrolled type 1, production outpaces both buffering and excretion. Blood pH falls. That is the acidosis in diabetic ketoacidosis, and it is what makes the condition dangerous rather than merely unpleasant.

At the same time, very high glucose draws large volumes of water into the urine, causing severe dehydration and loss of salts. Dehydration concentrates everything and accelerates the whole picture.

DKA is therefore three problems together: high glucose, high ketones with acid, and dehydration. It develops over hours and it is a medical emergency requiring urgent hospital treatment.

## Two things worth knowing

**Blood and urine ketone tests measure different things.** Blood strips measure beta-hydroxybutyrate, which is the main ketone present when things are actively getting worse. Urine strips measure acetoacetate, and they reflect a period of time already past rather than the current moment. Blood testing gives a more current picture.

**Glucose is not a reliable warning.** DKA can develop with glucose that is only moderately raised, particularly during illness, in pregnancy, and in people taking SGLT2 inhibitors. This is called euglycaemic DKA. It is uncommon, but it means a normal-looking glucose does not rule ketones out if you feel unwell.

## A worked example

Hypothetical: Nina has a stomach bug, is not eating, and assumes her insulin needs will be lower because no food is going in.

In fact illness raises cortisol and adrenaline, which increase both her glucose production and her insulin resistance. Her requirement has gone up, not down. Not eating also means her body turns to fat for fuel, increasing fatty acid supply to the liver.

So she has less insulin than she needs, at a time of increased fat delivery. Ketones rise. Nausea from the ketones makes her less inclined to drink, dehydration follows, and the process accelerates.

This is the most common route into DKA, and it is why illness is treated as a specific situation with its own plan rather than as a normal day with less food.

## In practice

This lesson explains a mechanism; it is not a management plan. Everyone with type 1 should have sick-day rules agreed with their diabetes team, covering when to test for ketones, what the results mean for them, and when to seek urgent help. That plan is individual and it is the thing to follow.

What this lesson should change is your model of the risk. Ketones are not a sign that glucose is high. They are a sign that insulin is absent, which is a different and more urgent problem, and it can arrive from a failed infusion site or a missed injection just as easily as from a meal.

If you have significant ketones and are vomiting, breathing deeply or feeling drowsy, that is an emergency. Get urgent medical help rather than working through it at home.', '["Ketones are made by the liver from fat, as a fuel the brain can use.", "Insulin normally restrains fat breakdown, so ketone production stays low.", "Without insulin the process runs unchecked and ketones accumulate as acid.", "High glucose alone is not DKA; it is the combination of ketones and acid that is dangerous.", "DKA is a medical emergency and needs urgent help, not managing alone at home."]'::json, 9, TRUE),
  (gen_random_uuid(), 'what-hba1c-actually-measures', 'What HbA1c actually measures', 'The chemistry behind the number, why it covers about three months, and the situations where it quietly misleads.', 'basics', 3, 4, '## The chemistry

Haemoglobin is the protein inside red blood cells that carries oxygen. Glucose in the blood attaches to it spontaneously, without any enzyme involved, in a process called glycation.

Two features of that reaction make it useful.

It is slow, so it reflects sustained exposure rather than momentary peaks. And it is effectively irreversible, so once a haemoglobin molecule is glycated it stays that way for the life of the cell.

The rate depends on how much glucose is present. More glucose in the blood means a greater proportion of haemoglobin ends up glycated. HbA1c is simply the percentage of haemoglobin that has been glycated, and in the international units it is reported in millimoles of glycated haemoglobin per mole of total.

## Why three months

Red blood cells have no nucleus and cannot repair themselves. They circulate for around 120 days before being removed by the spleen.

At any moment your bloodstream contains cells of every age from brand new to nearly four months old. A blood sample is therefore a mixture, and its overall glycation reflects the glucose those cells have been exposed to across their lifespans.

But it is not an even average across the period. Older cells have accumulated more glycation and there are fewer of them; newer cells dominate by number. The result is weighted towards the recent past.

Roughly, the most recent month accounts for about half of the result, the month before that about a quarter, and the two months before that the remainder.

This has a practical consequence. A change you made three weeks ago is already partly showing. And a good final fortnight before a clinic appointment does genuinely move the number, though not nearly as much as people hope.

## What it cannot see

Glycation depends on the concentration of glucose and the time it is present. It has no way of encoding order, timing or variability.

So a week spent steadily around 8 mmol/L (144 mg/dL) and a week alternating between 3 and 16 mmol/L (54 and 288 mg/dL) can produce the same HbA1c. One of those weeks contains dangerous lows and the other does not, and the number is silent on the difference.

This is the whole reason time in range exists as a separate measure. HbA1c and time in range answer different questions and are read together, not against each other.

CGM apps also report a glucose management indicator, which estimates what HbA1c would be given the CGM data. It is an estimate from a different measurement and will not match the lab exactly, which is expected rather than an error.

## When it misleads

Because the result depends on red cells surviving the full 120 days, anything that changes their lifespan changes the number without any change in glucose.

**Shorter cell survival gives a falsely low result.** Haemolytic anaemia, significant bleeding, iron deficiency once treatment starts, advanced kidney or liver disease, pregnancy in later stages, and recent transfusion.

**Longer cell survival gives a falsely high result.** Untreated iron or vitamin B12 deficiency, and a spleen that has been removed.

**Haemoglobin variants interfere with the assay itself.** Sickle cell trait, haemoglobin C, E and others, which are common in people of African, Mediterranean and South East Asian ancestry. The direction of error depends on the specific variant and the specific laboratory method.

There is also ordinary biological variation. Two people with identical average glucose can have HbA1c results differing by several units, because rates of glycation and cell turnover vary between individuals.

## A worked example

Hypothetical: Omar has had a difficult few months and expects a high result. It comes back lower than he predicted, and he is puzzled rather than pleased.

His CGM data for the same period shows frequent overnight lows. Those hours below range pulled his average exposure down, and the number reflects that faithfully.

The HbA1c was not wrong. It answered the question it is designed to answer, which is about average exposure, and that average was lowered by something he would not want to keep. Read alone it looked like an improvement. Read with the time-below-range figure alongside it, it looked like the opposite.

## In practice

Read HbA1c as one of a pair, never on its own. The companion question is always how much time was spent below range.

If your result is consistently far from what your CGM data suggests, that is worth raising, since one of the interference effects above may be involved and it is a testable question rather than a mystery.

And treat it as a slow measure. It is a good instrument for judging whether a change made two months ago worked. It is a poor one for judging last Tuesday.', '["Glucose sticks to haemoglobin slowly and permanently, in proportion to how much is around.", "Red blood cells live about 120 days, which sets the window.", "The recent month counts for roughly half of the result.", "Anything affecting red cell lifespan distorts it, in either direction.", "It says nothing about variability, which is why it is read alongside CGM data."]'::json, 10, TRUE),
  (gen_random_uuid(), 'how-cgm-sensors-work', 'How CGM sensors work', 'There is an enzyme and an electrode under your skin. Knowing what they are doing explains warm-up periods, compression lows and odd readings.', 'basics', 3, 4, '## What is actually under the skin

A continuous glucose monitor has a flexible filament, a few millimetres long and thinner than a hair, sitting in the layer of fat just under the skin. It is not in a blood vessel.

It sits in interstitial fluid, the fluid filling the spaces between cells. Glucose reaches that fluid by diffusing out of nearby capillaries.

On the surface of that filament is a coating containing an enzyme, most commonly glucose oxidase.

## The reaction

Glucose oxidase does one thing: it reacts with glucose and oxygen, producing gluconolactone and hydrogen peroxide.

Hydrogen peroxide is the useful part. Held at a set voltage, an electrode alongside the enzyme oxidises the peroxide, and that reaction releases electrons, which is a measurable electrical current.

More glucose in the fluid means more reaction, which means more peroxide, which means more current. The current is proportional to the glucose concentration, and the sensor''s job is to convert that current into a number using a calibration relationship established by the manufacturer.

So the device is not detecting glucose. It is measuring a current of a few billionths of an amp and inferring glucose from it. Almost every quirk of CGM behaviour comes from that indirection.

## Why blood flow matters

The reaction needs oxygen as well as glucose, and both arrive through the local capillaries. So the reading depends on that patch of tissue being adequately supplied.

This is the explanation for compression lows. Lie on a sensor for an hour and you compress the capillaries feeding it. Glucose delivery to that pocket of fluid falls, the local concentration drops, and the sensor faithfully reports what it is measuring, which is now no longer representative of your blood.

The pattern is recognisable: a drop that is unusually steep, occurring while asleep and on a sensor you have been lying on, which recovers rapidly and completely once you roll over. A real low does not resolve in three minutes without treatment.

This is also why cold hands and very poor peripheral circulation can make readings less reliable, and why sensor placement over an area with reasonable subcutaneous fat performs better than over lean or heavily worked muscle.

## The warm-up period

Inserting the filament causes a small injury. The tissue immediately around it responds with local inflammation, fluid shifts and minor bleeding, and the fluid in that space is briefly not representative of the wider interstitial fluid.

The warm-up hour or two allows this to settle and lets the sensor establish a stable baseline current. Readings taken before that settles are less reliable, which is why the first day of a sensor is often the least accurate day.

Over several days the opposite process gradually sets in. The body begins walling the filament off with fibrous tissue, which slowly impedes diffusion. This is one of the reasons sensors have a fixed wear life rather than running indefinitely.

## Calibration and interference

Early systems needed fingerstick calibration to anchor the current-to-glucose relationship. Modern sensors are factory calibrated, with the relationship established during manufacture and stabilised by improved enzyme chemistry.

Because the electrode detects any substance that oxidises at the same voltage, some compounds can interfere. Paracetamol, known as acetaminophen, was a well-known problem in older sensors, producing falsely high readings. Current generations use membranes that largely block it, though high doses of vitamin C are still noted as a possible interferent in some devices. Worth checking the specific guidance for the sensor you wear rather than assuming.

## A worked example

Hypothetical: Ravi wakes at 4am to an alarm reading 3.1 mmol/L (56 mg/dL) with a rapidly falling arrow. He feels completely normal.

He has been asleep on that arm. By the time he sits up and checks his blood with a fingerstick, the meter reads 6.4 mmol/L (115 mg/dL), and within a few minutes the sensor has climbed back to match.

Nothing malfunctioned. The sensor measured its local environment accurately, and that environment had been temporarily starved of blood supply by his own body weight.

Whether and when to confirm a reading with a fingerstick is part of the plan he has with his diabetes team. The mechanism is what explains why the two disagreed.

## In practice

Three things follow from knowing what is happening under the skin.

A sudden low overnight on a sensor you are lying on deserves a moment''s scepticism before it deserves a reaction, particularly if you feel nothing.

Rotating sites is not only about skin health; it also gives each area a chance to recover, and consistent placement in a well-perfused site gives more consistent results.

And the reading is an inference from a chemical reaction happening in a small pocket of fluid, not a direct measurement of your blood. It is usually an excellent inference. It is not the same thing.', '["The sensor measures a tiny electrical current, not glucose directly.", "An enzyme reacts with glucose and the reaction products are detected at an electrode.", "Readings depend on blood flow to that patch of skin, which is why lying on a sensor causes false lows.", "The warm-up period exists because the tissue around the filament is recovering from insertion.", "It measures interstitial fluid, so it lags behind blood by several minutes."]'::json, 11, TRUE)
ON CONFLICT (slug) DO UPDATE SET
  title             = EXCLUDED.title,
  summary           = EXCLUDED.summary,
  category          = EXCLUDED.category,
  difficulty        = EXCLUDED.difficulty,
  estimated_minutes = EXCLUDED.estimated_minutes,
  body              = EXCLUDED.body,
  key_takeaways     = EXCLUDED.key_takeaways,
  order_index       = EXCLUDED.order_index,
  published         = EXCLUDED.published;

